FoE = (85)
GeB = (70)
Inc = (89)
Cop = (90)

print("----Your Score----")
print("Foundation English :" , FoE )
print("General Business   :" ,GeB)
print("Introduction to Computer Systems :",Inc)
print("Computer Programming :",Cop)